name: limnojobs
channels:
- conda-forge
dependencies:
        - python=3.8.2
        - pandas
        - python-twitter
        - feedparser
        - colorama
        - argcomplete
        - pytest
        - pip
        - pip:
                - gspread
        

